### ISSUE TITLE
Input/Gamepad configuration

### ISSUE THREAD

**Issue by dinglyburrow** [drhelius/Gearboy#109]
I'm using a usb FC30 joypad. I can configure with other emulators mgba and altirra, but, Gearsystem/Gearboy won't accept new inputs.

**Comment by drhelius** [comment]
Can you share your system details?

When you say it won’t accept new inputs does it mean it doesn’t work at all or you can’t remap the buttons?

**Comment by dinglyburrow** [comment]
I'm running Windows 10 Home. Version 10.0.18362 Build 18362

It won't remap the buttons. The dialog appears "press any button on your gamepad" and it doesn't respond to input.

**Comment by drhelius** [comment]
Otherwise, are you getting any response with the default mapping?

It looks like [SDL included support for your controller in version 2.0.12](https://www.libsdl.org/tmp/SDL/WhatsNew.txt). I’m using this version in Mac and Linux but not in Windows.

I’ll rebuild the emulators with that version and get back to you.

**Comment by drhelius** [comment]
I have re-uploaded both binaries with the latest SDL version:

https://github.com/drhelius/Gearboy/releases/tag/gearboy-3.0.2
https://github.com/drhelius/Gearsystem/releases/tag/gearsystem-3.0.1

Could you try if this fixes the issue?

**Comment by dinglyburrow** [comment]
Awesome. That's fixed the issue. Thank you for the quick response.
